# Site settings
email: jcr@chairsandtables.org
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Journal
description: 
url: ""
twitter_username: 
default_img: 

# Profile settings
name: 
profile_img: 
profile: 
social:
  facebook: http://facebook.com/chairsandtablesorg
  twitter: http://twitter.com/chaisesettables
  instagram: http://instagram.com/chaisesettables
jcr-name: Jonathon Reed
jcr-profile_img: http://astheravenfli.es/img/journal/IMG_0010-JCR-2000-web.jpg
jcr-profile: Adventurer, educator, activist.
jcr-social:
  facebook: http://facebook.com/jonathonreed
  twitter: http://twitter.com/jonathoncomfort
  instagram: http://instagram.com/jonathonreed


# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
